# Generated by Django 5.0.2 on 2024-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwtapp", "0002_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="bio_link",
            field=models.URLField(null=True),
        ),
    ]
